FROM ubuntu:22.04

RUN apt update && apt install -y nginx sudo curl

# Weak user (bad practice)
RUN useradd admin && echo "admin:admin" | chpasswd

# Bad permissions
RUN chmod 777 /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
