- name: Container STIG Pipeline Scan
  hosts: all
  gather_facts: true

  tasks:
    - name: Scan insecure container
      command: /usr/bin/trivy image nginx-bad
      register: bad_scan

    - name: Save insecure report
      copy:
        content: "{{ bad_scan.stdout }}"
        dest: "/home/allensj/projects/security/container-stig-pipeline/reports/nginx-bad-{{ ansible_date_time.iso8601_basic }}.txt"

    - name: Scan secure container
      command: /usr/bin/trivy image nginx-secure
      register: secure_scan

    - name: Save secure report
      copy:
        content: "{{ secure_scan.stdout }}"
        dest: "/home/allensj/projects/security/container-stig-pipeline/reports/nginx-secure-{{ ansible_date_time.iso8601_basic }}.txt"
